using AMS.Base.DTO;
using AMS.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AMS.ServiceAccess
{
    public interface IGeneralRunningNumbersForAccountServiceAccess
    {
        IBaseEntityResponse<GeneralRunningNumbersForAccount> InsertGeneralRunningNumbersForAccount(GeneralRunningNumbersForAccount item);
        IBaseEntityResponse<GeneralRunningNumbersForAccount> UpdateGeneralRunningNumbersForAccount(GeneralRunningNumbersForAccount item);
        IBaseEntityResponse<GeneralRunningNumbersForAccount> DeleteGeneralRunningNumbersForAccount(GeneralRunningNumbersForAccount item);
        IBaseEntityCollectionResponse<GeneralRunningNumbersForAccount> GetBySearch(GeneralRunningNumbersForAccountSearchRequest searchRequest);
        IBaseEntityResponse<GeneralRunningNumbersForAccount> SelectByID(GeneralRunningNumbersForAccount item);
        IBaseEntityCollectionResponse<GeneralRunningNumbersForAccount> GetGeneralRunningNumbersForAccountList(GeneralRunningNumbersForAccountSearchRequest searchRequest);
        IBaseEntityResponse<GeneralRunningNumbersForAccount> GetAutoGeneratedRequirementNumber(GeneralRunningNumbersForAccount item);
    }
}
